title: МЭРКА.РФ
email: she@mayorness.ru
description: Юлия Ганусова. Красноярск  
baseurl: ""
url: "http://мэрка.рф"

google_analytics: UA-107038914-1

# Build settings
markdown: kramdown
theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
